using System;
using System.Collections.Generic;

#nullable disable

namespace AfinitiPortalAPI.Data.PortalDBContext.Entity
{
    public partial class PaycomEmployeeFull
    {
        public int CurrentWorkinFlag { get; set; }
        public DateTime EtlDate { get; set; }
        public string EmployeeCode { get; set; }
        public string WorkEmail { get; set; }
        public string FullName { get; set; }
        public string EmployeeName { get; set; }
        public string Nickname { get; set; }
        public string Firstname { get; set; }
        public string Middlename { get; set; }
        public string Lastname { get; set; }
        public string AllWorkStatus { get; set; }
        public string ChangeStatus { get; set; }
        public string WorkStatus { get; set; }
        public DateTime? HireDate { get; set; }
        public DateTime? TerminationDate { get; set; }
        public DateTime? FirstHireDate { get; set; }
        public string TerminationMonth { get; set; }
        public DateTime? RehireDate { get; set; }
        public string HireMonth { get; set; }
        public long? HireRank { get; set; }
        public string FirstSupervisorCodeCheck { get; set; }
        public string FirstSupervisorCheck { get; set; }
        public int? TotalHeadcount { get; set; }
        public int? DirectReports { get; set; }
        public string PeopleManager { get; set; }
        public string DepartmentCode { get; set; }
        public string Department { get; set; }
        public string SubDepartment { get; set; }
        public string Team { get; set; }
        public string RedBlueTeamFlag { get; set; }
        public string ActualMaritalStatus { get; set; }
        public string ActualMaritalStatusDescription { get; set; }
        public string Level { get; set; }
        public string Clocksequencenumber { get; set; }
        public string SubDepartmentCode { get; set; }
        public string TeamCode { get; set; }
        public string EmploymentType { get; set; }
        public string PositionTitle { get; set; }
        public string Position { get; set; }
        public string BusinessTitle { get; set; }
        public string PositionId { get; set; }
        public string PositionSeatTitle { get; set; }
        public string PositionCode { get; set; }
        public string PositionSeatNumber { get; set; }
        public string PositionFamilyCode { get; set; }
        public string PositionFamily { get; set; }
        public string PositionFamilyName { get; set; }
        public DateTime? EmployeeAdded { get; set; }
        public DateTime? SnapshotHireDate { get; set; }
        public int HireDateL12mFlag { get; set; }
        public int TerminationDateL12mFlag { get; set; }
        public string TerminationReason { get; set; }
        public string LengthOfServiceSinceRehire { get; set; }
        public bool? HourlyOrSalary { get; set; }
        public string EmployeeGlCode { get; set; }
        public string LaborAllocationDetails { get; set; }
        public string PersonalEmail { get; set; }
        public int? FulltimeOrParttime { get; set; }
        public bool? HasDirectDeposit { get; set; }
        public DateTime? BirthDate { get; set; }
        public int? Age { get; set; }
        public decimal? AfinitiAge { get; set; }
        public string Gender { get; set; }
        public string GenderDesc { get; set; }
        public int? PrimaryPhoneType { get; set; }
        public string PrimaryPhone { get; set; }
        public int? SecondaryPhoneType { get; set; }
        public string SecondaryPhone { get; set; }
        public string Zipcode { get; set; }
        public string EmployeeStatus { get; set; }
        public bool? EmployeeType1099 { get; set; }
        public string EthnicBackground { get; set; }
        public DateTime? LastPayChange { get; set; }
        public DateTime? LastPositionChangeDate { get; set; }
        public DateTime? LastReview { get; set; }
        public string State { get; set; }
        public string LocationRaw { get; set; }
        public string Country { get; set; }
        public int? CompanyLocationId { get; set; }
        public string DolStatus { get; set; }
        public string ExemptStatus { get; set; }
        public string Street { get; set; }
        public DateTime? Changetime { get; set; }
        public int? MaxDay { get; set; }
        public int? MinDay { get; set; }
        public bool? NewHire { get; set; }
        public DateTime? NewHireReportDate { get; set; }
        public DateTime? RehireDateRaw { get; set; }
        public bool? ReportNewHire { get; set; }
        public DateTime? PreviousTerminationDate { get; set; }
        public DateTime? NextReview { get; set; }
        public string PayClass { get; set; }
        public string PayFrequency { get; set; }
        public string SupervisorApproval { get; set; }
        public DateTime? MostRecentCheckDate { get; set; }
        public string NineLevelBelowCeoCode { get; set; }
        public string NineLevelBelowCeo { get; set; }
        public string EigthLevelBelowCeoCode { get; set; }
        public string EigthLevelBelowCeo { get; set; }
        public string SevenLevelBelowCeoCode { get; set; }
        public string SevenLevelBelowCeo { get; set; }
        public string SixLevelBelowCeoCode { get; set; }
        public string SixLevelBelowCeo { get; set; }
        public string FiveLevelBelowCeoCode { get; set; }
        public string FiveLevelBelowCeo { get; set; }
        public string FourLevelBelowCeoCode { get; set; }
        public string FourLevelBelowCeo { get; set; }
        public string ThreeLevelBelowCeoCode { get; set; }
        public string ThreeLevelBelowCeo { get; set; }
        public string TwoLevelBelowCeoCode { get; set; }
        public string TwoLevelBelowCeo { get; set; }
        public string OneLevelBelowCeoCode { get; set; }
        public string OneLevelBelowCeo { get; set; }
        public string CeoCode { get; set; }
        public string Ceo { get; set; }
        public string FirstSupervisorCode { get; set; }
        public string FirstSupervisor { get; set; }
        public string SecondSupervisorCode { get; set; }
        public string SecondSupervisor { get; set; }
        public string ThirdSupervisorCode { get; set; }
        public string ThirdSupervisor { get; set; }
        public string FourthSupervisorCode { get; set; }
        public string FourthSupervisor { get; set; }
        public string FifthSupervisorCode { get; set; }
        public string FifthSupervisor { get; set; }
        public string SixthSupervisorCode { get; set; }
        public string SixthSupervisor { get; set; }
        public string SeventhSupervisorCode { get; set; }
        public string SeventhSupervisor { get; set; }
        public string EighthSupervisorCode { get; set; }
        public string EighthSupervisor { get; set; }
        public string NinthSupervisorCode { get; set; }
        public string NinthSupervisor { get; set; }
        public string TenthSupervisorCode { get; set; }
        public string TenthSupervisor { get; set; }
        public int? NineLevelBelowCeoCodeDre { get; set; }
        public int? EigthLevelBelowCeoCodeDre { get; set; }
        public int? SevenLevelBelowCeoCodeDre { get; set; }
        public int? SixLevelBelowCeoCodeDre { get; set; }
        public int? FiveLevelBelowCeoCodeDre { get; set; }
        public int? FourLevelBelowCeoCodeDre { get; set; }
        public int? ThreeLevelBelowCeoCodeDre { get; set; }
        public int? TwoLevelBelowCeoCodeDre { get; set; }
        public int? OneLevelBelowCeoCodeDre { get; set; }
        public int? CeoDre { get; set; }
        public decimal? AfinitiTotalAge { get; set; }
        public string RoleName { get; set; }
        public string Service { get; set; }
        public string ServiceGroup { get; set; }
        public string Portfolio { get; set; }
        public string City { get; set; }
        public string RawLegalEntity { get; set; }
        public string LegalCountry { get; set; }
        public string LegalEntity { get; set; }
        public string NtLogin { get; set; }
        public string FirstSupervisorWorkStatus { get; set; }
        public string FirstSupervisorDepartment { get; set; }
        public string FirstSupervisorWorkEmail { get; set; }
        public string OneLevBelowCeoDepartment { get; set; }
        public int SupervisorOfOneself { get; set; }
        public string SubDepartmentDisplayName { get; set; }
    }
}
